### ISSUE TITLE
publish Official GitHub action

### ISSUE THREAD

**Issue by frode-carlsen** [microsoft/ApplicationInspector#136]
**Is your feature request related to a problem? Please describe.**
github actions have become our default build pipeline setup. It would be very useful if this tool could be applied as a github action to scan for vulnerabilities, and possibly publish a report to a github pages

**Describe the solution you'd like**
Create a github action to deploy Application Inspector

**Comment by guyacosta** [comment]
We are looking into this with GitHub.

**Comment by geekdave** [comment]
@guyacosta As a recent GitHub Actions Convert, I'm also keenly interested in this.  Wondering if this will depend on docker support being shipped as described in https://github.com/microsoft/ApplicationInspector/issues/100, or whether this will run directly on the runner VM with no containerization?

**Comment by gfs** [comment]
You should be able to set something up pretty trivially with the dotnet tool now if actions has similar functionality to azure pipelines. 

Make sure you have the .NET Core 3.1 runtime and then 

`dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI`

Then you should be able to just

`AppInspector [args]`

https://www.nuget.org/packages/Microsoft.CST.ApplicationInspector.CLI/

**Comment by gfs** [comment]
As noted above you can do this in the base runner in a pipeline without having to run in a VM. That's probably a better approach than using a docker image in a pipeline.

**Comment by gfs** [comment]
Here's the yml formatted workaround for now you can use in your GitHub actions pipeline.

```yml
steps:
- uses: actions/checkout@master
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.300'
- run: dotnet tool install -g Microsoft.CST.ApplicationInspector.CLI
- run: AppInspector [args]
```
