### ISSUE TITLE
[Request] Azure DevOps Extension

### ISSUE THREAD

**Issue by ArieHein** [microsoft/ApplicationInspector#76]
Would be nice to have an Azure DevOps extension doing all the boilerplate instead of 
writing a few commands to invoke with all variables

**Comment by guyacosta** [comment]
Great idea.  Have one started but not published.  TBD.

**Comment by SebastianSchuetze** [comment]
@guyacosta I might help if you have something I can participate. I created some pipeline extensions myself and this could be part of it.

**Comment by guyacosta** [comment]
@Sebastion.  Apologies on the delayed response.  Send me your contact info to discuss by connecting with me on LinkedIn.

**Comment by SebastianSchuetze** [comment]
@guyacosta connection request is sent.

**Comment by guyacosta** [comment]
Updates to follow.  Connecting with Sebastian this week.

**Comment by guyacosta** [comment]
Any takers?

**Comment by SebastianSchuetze** [comment]
let's do it!

**Comment by guyacosta** [comment]
This is in progress.  Updates soon.

**Comment by gfs** [comment]
This should be trivial now. 

Ensure you have .NET Core 3.1 SDK.

`dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI`

`AppInspector [args]`

**Comment by SebastianSchuetze** [comment]
@guyacosta any updates on how / when we should proceed?

**Comment by gfs** [comment]
@SebastianSchuetze it looks like pipeline extensions have to be written in Node.

https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

For now you can use this in your pipeline.yml file

```
- task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

- script: 'dotnet tool install -g Microsoft.CST.ApplicationInspector.CLI'
      displayName: 'Install Application Inspector'

- script: 'AppInspector [args]'
      displayName: 'Run Application Inspector'
```
